services:
  - type: web
    name: whatsapp-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook.py"
    envVars:
      - key: PORT
        value: 10000
